//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_INFO
    {
        public int MLSID { get; set; }
        public Nullable<int> mls { get; set; }
        public string MLS_NAME { get; set; }
        public string FILE_LOCATION { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> FULL_INC { get; set; }
        public Nullable<System.DateTime> DATE_RUN { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string ml_number { get; set; }
        public string oh_st_date { get; set; }
        public string oh_end_date { get; set; }
        public string oh_time { get; set; }
        public string oh_end_time { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
