//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_DATA
    {
        public Nullable<int> mls { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string ml_number { get; set; }
        public Nullable<System.DateTime> oh_st_date { get; set; }
        public Nullable<System.DateTime> oh_end_date { get; set; }
        public string oh_time { get; set; }
        public string oh_end_time { get; set; }
        public string comments { get; set; }
    }
}
