//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT_DATA
    {
        public Nullable<int> MLS { get; set; }
        public Nullable<System.DateTime> DATE_ADDED { get; set; }
        public string AGENTID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string PHONE_AC { get; set; }
        public string PHONE { get; set; }
        public string CELL_PHONE_AC { get; set; }
        public string CELL_PHONE { get; set; }
        public string FAX_AC { get; set; }
        public string FAX { get; set; }
        public string ADDRESS_DIR_PRE { get; set; }
        public string ADDRESS_DIR_SUF { get; set; }
        public string ADDRESS_NUM { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_SUF { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string TITLE { get; set; }
        public string DESIGNATIONS { get; set; }
        public string OFFICEID { get; set; }
        public string FIRMID { get; set; }
        public string AGENT_STATUS { get; set; }
        public string Facebook_URL { get; set; }
        public byte[] profile_Picture { get; set; }
        public string AGENT_PASSWORD { get; set; }
        public string AGENT_TITLE { get; set; }
        public string AGENT_LANGUAGE { get; set; }
        public string AGENT_TXT { get; set; }
        public string AGENT_BIO_TEXT { get; set; }
        public string AGENT_BLOG { get; set; }
        public string Twitter_URL { get; set; }
        public string Google_Plus_URL { get; set; }
        public string LinkedIn_URL { get; set; }
    }
}
