//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT_INFO
    {
        public int AGENTID { get; set; }
        public string AGENT_TITLE { get; set; }
        public Nullable<int> OWNERBROKER { get; set; }
        public string AGENT_POSITION { get; set; }
        public string AGENT_FNAME { get; set; }
        public string AGENT_LNAME { get; set; }
        public Nullable<int> COMPID { get; set; }
        public Nullable<int> OFFICEID { get; set; }
        public string AGENT_PHONE { get; set; }
        public string AGENT_CELL { get; set; }
        public string AGENT_TXT { get; set; }
        public string AGENT_FAX { get; set; }
        public string AGENT_EMAIL { get; set; }
        public string AGENT_LANGUAGE { get; set; }
        public Nullable<int> AGENT_PIC_TH { get; set; }
        public Nullable<int> AGENT_PIC { get; set; }
        public Nullable<int> AGENT_BIOTYPE { get; set; }
        public string AGENT_BIO_TEXT { get; set; }
        public string AGENT_URL { get; set; }
        public string RETS_ID { get; set; }
        public string AGENT_LI_ID { get; set; }
        public string AGENT_BROOKLYN_ID { get; set; }
        public Nullable<System.DateTime> AGENT_AOM { get; set; }
        public Nullable<System.DateTime> AGENT_TP { get; set; }
        public Nullable<System.DateTime> AGENT_TP_C { get; set; }
        public Nullable<System.DateTime> AGENT_TL { get; set; }
        public Nullable<System.DateTime> AGENT_TL_C { get; set; }
        public Nullable<int> AGENT_CHECKEDTP { get; set; }
        public Nullable<int> AGENT_CHECKEDTL { get; set; }
        public string AGENT_AWARDS { get; set; }
        public Nullable<int> AGENT_WEBSITE { get; set; }
        public Nullable<int> AGENT_ADDT_PAGE { get; set; }
        public string AGENT_ADDT_PAGE_LINK { get; set; }
        public Nullable<System.DateTime> AGENT_DATE { get; set; }
        public Nullable<decimal> AGENT_PRODUCTION { get; set; }
        public string AGENT_DESIGNATIONS { get; set; }
        public Nullable<int> SHOWIT { get; set; }
        public Nullable<int> AGENT_BLOG { get; set; }
        public string AGENT_SERVES { get; set; }
        public string AGENT_PASSWORD { get; set; }
        public string AGENT_LISTINGBOOK { get; set; }
        public string AGENT_LB_ID { get; set; }
        public string AGENT_RP_ID { get; set; }
        public Nullable<int> AGENT_RP_DISPLAY { get; set; }
        public string AGENT_FB_URL { get; set; }
        public Nullable<int> AGENT_FEATURED { get; set; }
        public string AGENT_FEATURED_TEXT { get; set; }
        public string CO_AGENT_FNAME { get; set; }
        public string CO_AGENT_LNAME { get; set; }
        public string CO_AGENT_ID { get; set; }
        public string AGENT_SLOGAN { get; set; }
        public Nullable<int> AGENT_IMAGE { get; set; }
        public string AGENT_IMAGE_LINK { get; set; }
        public string AGENT_EMAIL_2 { get; set; }
        public Nullable<int> AGENT_NYSMLS { get; set; }
        public byte[] AGENT_ImageNew { get; set; }
        public string Agent_Twitter_URL { get; set; }
        public string Agent_Youtube_URL { get; set; }
        public string Agent_Instagram_URL { get; set; }
    }
}
