//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class bob_form
    {
        public int userid { get; set; }
        public string title { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string designations { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string cell_phone { get; set; }
        public string phone { get; set; }
        public string mls { get; set; }
        public string mls_id { get; set; }
        public string url { get; set; }
    }
}
