//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_INFO
    {
        public int COMPID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string MLS_COMP_CODE { get; set; }
        public Nullable<int> BROOKLYN_ID { get; set; }
        public string RETS_IDs { get; set; }
        public Nullable<int> COMPANY_STATUS { get; set; }
        public Nullable<int> COMPANY_TP { get; set; }
        public Nullable<int> COMPANY_AOM { get; set; }
        public Nullable<int> COMPANY_RATES { get; set; }
        public Nullable<int> MLS_LI { get; set; }
        public Nullable<int> MLS_BROOKLYN { get; set; }
        public Nullable<int> SAUNDERS { get; set; }
        public string COMPANY_URL { get; set; }
        public Nullable<int> ERA_TALKING { get; set; }
        public Nullable<int> VIRTUAL_TOUR { get; set; }
        public Nullable<int> OFFICE_PAGES { get; set; }
        public string OFFICE_URL { get; set; }
        public string OFFICE_DRIVE { get; set; }
        public Nullable<int> OFFICE_ADDITIONAL_PAGE { get; set; }
        public Nullable<int> AGENT_PAGES { get; set; }
        public string AGENT_URL { get; set; }
        public string AGENT_DRIVE { get; set; }
        public Nullable<int> ADDITIONAL_PAGE { get; set; }
        public Nullable<int> PROSPECTMATCH { get; set; }
        public Nullable<int> PRODUCTION { get; set; }
        public Nullable<int> RENTALPERIODS { get; set; }
        public Nullable<int> MLS_STATS { get; set; }
        public Nullable<int> WEB_STATS { get; set; }
        public Nullable<int> TESTIMONIALS { get; set; }
        public Nullable<int> OFFICE_PIC_W { get; set; }
        public Nullable<int> OFFICE_PIC_H { get; set; }
        public Nullable<int> AGENT_PIC_W { get; set; }
        public Nullable<int> AGENT_PIC_H { get; set; }
        public Nullable<int> AGENT_PIC_SM_W { get; set; }
        public Nullable<int> AGENT_PIC_SM_H { get; set; }
        public Nullable<int> TESTIMONIAL_W { get; set; }
        public Nullable<int> TESTIMONIAL_H { get; set; }
        public Nullable<int> ADDTLIMGS { get; set; }
        public Nullable<int> FLOORPLANS { get; set; }
        public Nullable<int> LANDINGS { get; set; }
        public Nullable<int> SHOWTHEM { get; set; }
        public Nullable<int> NEWSLETTERS { get; set; }
        public Nullable<int> OFFICE_BLOGS { get; set; }
        public Nullable<int> AGENT_BLOGS { get; set; }
        public Nullable<int> VENDORS { get; set; }
        public Nullable<int> linktable { get; set; }
        public Nullable<int> SITEMAP { get; set; }
        public string SITE_DRIVE { get; set; }
        public Nullable<int> HP_MESSAGE { get; set; }
        public Nullable<int> PASSWORDS { get; set; }
        public Nullable<int> INTRANET { get; set; }
        public Nullable<int> REALPING { get; set; }
        public Nullable<int> professionals { get; set; }
        public Nullable<int> marketingreports { get; set; }
        public Nullable<int> seotowns { get; set; }
        public Nullable<int> developments { get; set; }
        public Nullable<int> HEADLINES { get; set; }
        public Nullable<int> VIDEOS { get; set; }
        public Nullable<int> towns { get; set; }
    }
}
