//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformation
    {
        public int ID { get; set; }
        public string SellAHome { get; set; }
        public string BuyAHome { get; set; }
        public string RealtysBuyersGuide { get; set; }
        public string MarketAnalysisOfMyHome { get; set; }
        public string CareerInRealEstate { get; set; }
        public string Ml_number { get; set; }
        public string Mls_ID { get; set; }
        public string CompID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string ContactMsg { get; set; }
    }
}
