//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class decoder_key
    {
        public int id { get; set; }
        public string field_name { get; set; }
        public string field_value { get; set; }
        public string new_value { get; set; }
        public string default_value { get; set; }
        public Nullable<int> mls { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
