//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fieldname
    {
        public Nullable<int> txtid { get; set; }
        public int fieldid { get; set; }
        public string fieldname1 { get; set; }
        public Nullable<int> fieldtypeid { get; set; }
    }
}
