//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLS_IMAGES_INFO
    {
        public int MLSID { get; set; }
        public Nullable<int> mls { get; set; }
        public string MLS_NAME { get; set; }
        public string FILE_LOCATION { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> FULL_INC { get; set; }
        public Nullable<System.DateTime> DATE_RUN { get; set; }
        public Nullable<int> ACTIVE { get; set; }
        public string media_id { get; set; }
        public string media_la_code { get; set; }
        public string media_order { get; set; }
        public string media_remarks { get; set; }
        public string media_type { get; set; }
        public string mls_account { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
