//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILEML
    {
        public int mobileID { get; set; }
        public string CODE { get; set; }
        public string bkcode { get; set; }
        public Nullable<int> COMPID { get; set; }
        public string COMPANY { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> LOGO { get; set; }
        public Nullable<int> FONT { get; set; }
        public Nullable<int> AGENT_SEARCH { get; set; }
        public Nullable<int> OFFICE_SEARCH { get; set; }
        public string MAIN_URL { get; set; }
        public string MOBILE_URL { get; set; }
        public string BYLINE { get; set; }
        public string googlekey { get; set; }
        public string resultspage { get; set; }
        public Nullable<int> bkmls { get; set; }
        public Nullable<int> limls { get; set; }
        public string bkresultspage { get; set; }
        public Nullable<int> agentid { get; set; }
    }
}
