//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobileapp_users
    {
        public int userid { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string color { get; set; }
        public string agentid { get; set; }
        public Nullable<int> mls { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string provider { get; set; }
    }
}
