//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NYSML
    {
        public int nysmlsid { get; set; }
        public string Brokername { get; set; }
        public string brokercode { get; set; }
        public string officecode { get; set; }
        public string mls { get; set; }
        public Nullable<System.DateTime> daterun { get; set; }
        public Nullable<int> active { get; set; }
        public string url { get; set; }
        public string pagename { get; set; }
        public Nullable<int> rpcompid { get; set; }
        public Nullable<int> rpofficeid { get; set; }
    }
}
