//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICE_DATA
    {
        public Nullable<int> MLS { get; set; }
        public Nullable<System.DateTime> DATE_ADDED { get; set; }
        public string OFFICEID { get; set; }
        public string OFFICE_NAME { get; set; }
        public string ADDRESS_NUM { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE_AC { get; set; }
        public string PHONE { get; set; }
        public string FAX_AC { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string FIRMID { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    }
}
