//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class rets_test_table
    {
        public int mls { get; set; }
        public string ml_number { get; set; }
        public string agent_name { get; set; }
        public string officeid { get; set; }
        public string firmid { get; set; }
    }
}
