//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCH
    {
        public Nullable<int> USER_ID { get; set; }
        public string AGENT_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string SEARCHNAME { get; set; }
        public string siteURL { get; set; }
        public string SENDING_EMAIL { get; set; }
        public string MLSTYPE { get; set; }
        public int SEARCH_ID { get; set; }
        public string COUNTY { get; set; }
        public string CITY { get; set; }
        public string PRICE_LOW { get; set; }
        public string PRICE_HIGH { get; set; }
        public string BEDS_LOW { get; set; }
        public string BEDS_HIGH { get; set; }
        public string FULL_BATHS_LOW { get; set; }
        public string FULL_BATHS_HIGH { get; set; }
        public string HALF_BATHS_LOW { get; set; }
        public string HALF_BATHS_HIGH { get; set; }
        public string FAMILIES_LOW { get; set; }
        public string FAMILIES_HIGH { get; set; }
        public string SQFT_LOW { get; set; }
        public string SQFT_HIGH { get; set; }
        public string ZIPCODE { get; set; }
        public string HANDICAP { get; set; }
        public string GREENFEATURES { get; set; }
        public string NEWCONSTRUCT { get; set; }
        public string WATERFRONT { get; set; }
        public string WATERVIEW { get; set; }
        public string ADULT { get; set; }
        public string GARAGE { get; set; }
        public string BASEMENT { get; set; }
        public string POOL { get; set; }
        public string TENNIS { get; set; }
        public string FORECLOSURE { get; set; }
        public string SHORTSALE { get; set; }
        public string STYLES { get; set; }
        public string SCHOOLS { get; set; }
        public string PARKING { get; set; }
        public string SALE_RENT { get; set; }
        public string LOADING_DOCK { get; set; }
        public string PROP_TYPE { get; set; }
        public string BUS_TYPE { get; set; }
        public string BROKER_CODE { get; set; }
        public string LTYPE { get; set; }
        public string ACRES_LOW { get; set; }
        public string ACRES_HIGH { get; set; }
        public string company_id { get; set; }
    }
}
