//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLD_DATA
    {
        public Nullable<int> mls { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string retsysid { get; set; }
        public string ml_number { get; set; }
        public Nullable<System.DateTime> list_date { get; set; }
        public Nullable<float> list_price { get; set; }
        public Nullable<System.DateTime> sell_date { get; set; }
        public Nullable<float> sell_price { get; set; }
        public string list_type { get; set; }
        public string address { get; set; }
        public string street_number { get; set; }
        public string unit_number { get; set; }
        public string street { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string county { get; set; }
        public string acres { get; set; }
        public string baths { get; set; }
        public string beds { get; set; }
        public string bus_type { get; set; }
        public string construct_type { get; set; }
        public string exterior { get; set; }
        public string families { get; set; }
        public string foreclosure { get; set; }
        public string handicap { get; set; }
        public string heat { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public string lot_size { get; set; }
        public string lot_sqft { get; set; }
        public string parking { get; set; }
        public string rooms { get; set; }
        public string sale_type { get; set; }
        public string short_sale { get; set; }
        public string style { get; set; }
        public string taxes { get; set; }
        public string zoning { get; set; }
        public string list_agent_id { get; set; }
        public string list_agent { get; set; }
        public string co_list_agent_id { get; set; }
        public string co_list_agent { get; set; }
        public string sell_agent_id { get; set; }
        public string sell_agent { get; set; }
        public string co_sell_agent_id { get; set; }
        public string co_sell_agent { get; set; }
        public string realtor { get; set; }
        public string realtor_code { get; set; }
        public string list_branch { get; set; }
        public string sell_realtor { get; set; }
        public string sell_realtor_code { get; set; }
        public string sell_branch { get; set; }
    }
}
