//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class txtfile
    {
        public string filename { get; set; }
        public string ColNameHeader { get; set; }
        public string Format { get; set; }
        public string MaxScanRows { get; set; }
        public string CharacterSet { get; set; }
        public string filelocation { get; set; }
        public int txtid { get; set; }
    }
}
