//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public int USERID { get; set; }
        public Nullable<int> USER_LEVEL { get; set; }
        public Nullable<int> COMPID { get; set; }
        public Nullable<int> AGENTID { get; set; }
        public Nullable<int> OFFICEID { get; set; }
        public Nullable<System.DateTime> LAST_LOGGED { get; set; }
        public string LAST_LOGGED_IP { get; set; }
        public string LAST_LOGGED_PC { get; set; }
        public string USER_EMAIL { get; set; }
    }
}
