//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class virtual_tours_info
    {
        public int MLSID { get; set; }
        public Nullable<int> mls { get; set; }
        public string mls_name { get; set; }
        public string file_location { get; set; }
        public string file_name { get; set; }
        public Nullable<int> full_inc { get; set; }
        public Nullable<System.DateTime> date_run { get; set; }
        public Nullable<int> active { get; set; }
        public string ml_number { get; set; }
        public string toururl { get; set; }
        public string datemodified { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    }
}
