//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Century21.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class virtual_tours
    {
        public Nullable<int> mls { get; set; }
        public string ml_number { get; set; }
        public string toururl { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
    }
}
